import Foundation

struct Localizer {
    var language: AppLanguage

    func text(_ key: String) -> String {
        dictionaries[language]?[key] ?? dictionaries[.english]?[key] ?? key
    }

    func percent(_ value: Double) -> String {
        "\(Int((value * 100).rounded()))%"
    }
}

private let dictionaries: [AppLanguage: [String: String]] = [
    .english: [
        "app.name": "GlowMate",
        "tab.meter": "Meter",
        "tab.light": "Light",
        "tab.scenes": "Scenes",
        "tab.records": "Records",
        "tab.settings": "Settings",
        "meter.title": "Soft light meter",
        "meter.subtitle": "Offline camera metering for better screen fill light.",
        "meter.permission.title": "Camera access is needed",
        "meter.permission.body": "GlowMate measures brightness from the live preview on this device. Nothing is uploaded.",
        "meter.permission.button": "Allow Camera",
        "meter.demo": "Screenshot demo",
        "meter.current": "Current issue",
        "meter.recommendation": "Recommended setup",
        "meter.apply": "Apply light",
        "meter.applied": "Applied to Light",
        "meter.noFrame": "Waiting for local light sample",
        "issue.tooDark": "Face area is dark",
        "issue.tooBright": "Light is too strong",
        "issue.cool": "Light feels cool",
        "issue.yellow": "Light is yellow",
        "issue.balanced": "Light is balanced",
        "reason.tooDark": "Raise screen light and keep it close to soften shadows.",
        "reason.tooBright": "Lower fill light to avoid flat highlights.",
        "reason.cool": "Use warm skin light to bring back natural color.",
        "reason.yellow": "Use natural white to reduce the warm cast.",
        "reason.balanced": "Keep a moderate fill light for gentle eye catchlights.",
        "headline.tooDark": "Warm skin light, stronger",
        "headline.tooBright": "Natural light, softer",
        "headline.cool": "Warm skin light",
        "headline.yellow": "Natural white correction",
        "headline.balanced": "Balanced soft light",
        "tone.warmSkin": "Warm Skin",
        "tone.naturalWhite": "Natural White",
        "tone.coolWhite": "Cool White",
        "tone.blush": "Blush",
        "distance.close": "25-35 cm",
        "distance.table": "35-50 cm",
        "distance.product": "40-60 cm",
        "distance.meeting": "45-70 cm",
        "guidance.selfie": "Hold the phone slightly above eye level and let the screen face you.",
        "guidance.food": "Light from the front side and avoid blocking the plate with the phone.",
        "guidance.product": "Move the light to the front-left to reduce heavy shadows.",
        "guidance.meeting": "Keep screen light gentle so your face stays natural on video.",
        "guidance.nightRoom": "Use warm light close to the face to keep the room mood.",
        "light.title": "Screen soft light",
        "light.subtitle": "Tune brightness and tone, then open a full-screen fill light.",
        "light.brightness": "Brightness",
        "light.tone": "Tone",
        "light.distance": "Distance",
        "light.start": "Start soft light",
        "light.close": "Close",
        "light.full.title": "Soft light active",
        "light.saved": "Saved locally",
        "light.torch": "Rear torch",
        "light.torch.on": "Torch on",
        "light.torch.off": "Torch off",
        "light.torch.unavailable": "Torch unavailable on this device",
        "scene.title": "Scene presets",
        "scene.subtitle": "Choose a practical setup and GlowMate saves it locally.",
        "scene.selfie": "Selfie portrait",
        "scene.selfie.subtitle": "Warm face light and soft shadows",
        "scene.food": "Food photo",
        "scene.food.subtitle": "Cleaner color for dim restaurants",
        "scene.product": "Product shot",
        "scene.product.subtitle": "Sharper details and lower shadows",
        "scene.meeting": "Video meeting",
        "scene.meeting.subtitle": "Gentle constant light",
        "scene.nightRoom": "Night room",
        "scene.nightRoom.subtitle": "Warm fill for low light rooms",
        "scene.selected": "Preset applied",
        "records.title": "Local records",
        "records.subtitle": "Recent setups saved only on this iPhone.",
        "records.empty": "Apply a recommendation or preset to create a record.",
        "records.restored": "Record restored",
        "records.clear": "Clear records",
        "settings.title": "Settings",
        "settings.subtitle": "Local preferences and app information.",
        "settings.language": "Language",
        "settings.system": "System default",
        "settings.privacy": "Privacy Policy",
        "settings.support": "Support",
        "settings.version": "Version 1.0.0",
        "settings.localOnly": "Local-only app. No account, analytics, ads, or backend.",
        "settings.languageChanged": "Language saved",
        "common.score": "Score",
        "common.apply": "Apply",
        "common.current": "Current",
        "common.done": "Done"
    ],
    .simplifiedChinese: [
        "app.name": "柔光伴侣",
        "tab.meter": "测光",
        "tab.light": "柔光",
        "tab.scenes": "场景",
        "tab.records": "记录",
        "tab.settings": "设置",
        "meter.title": "柔光测光",
        "meter.subtitle": "用本地相机预览测光，推荐更自然的屏幕补光。",
        "meter.permission.title": "需要相机权限",
        "meter.permission.body": "柔光伴侣只在本机用预览画面估算亮度，不会上传照片。",
        "meter.permission.button": "允许相机",
        "meter.demo": "截图演示",
        "meter.current": "当前问题",
        "meter.recommendation": "推荐参数",
        "meter.apply": "应用补光",
        "meter.applied": "已应用到柔光",
        "meter.noFrame": "正在等待本地光线样本",
        "issue.tooDark": "脸部偏暗",
        "issue.tooBright": "光线过强",
        "issue.cool": "光线偏冷",
        "issue.yellow": "光线偏黄",
        "issue.balanced": "光线均衡",
        "reason.tooDark": "提高屏幕亮度并靠近一点，可以柔化阴影。",
        "reason.tooBright": "降低补光强度，避免高光太平。",
        "reason.cool": "使用暖肤光，让肤色更自然。",
        "reason.yellow": "使用自然白，减轻环境黄光。",
        "reason.balanced": "保持中等补光，增加柔和眼神光。",
        "headline.tooDark": "暖肤光，亮一点",
        "headline.tooBright": "自然白，柔一点",
        "headline.cool": "暖肤光",
        "headline.yellow": "自然白校正",
        "headline.balanced": "均衡柔光",
        "tone.warmSkin": "暖肤光",
        "tone.naturalWhite": "自然白",
        "tone.coolWhite": "冷白光",
        "tone.blush": "蜜桃光",
        "distance.close": "25-35 厘米",
        "distance.table": "35-50 厘米",
        "distance.product": "40-60 厘米",
        "distance.meeting": "45-70 厘米",
        "guidance.selfie": "手机略高于眼睛，让屏幕正对脸部。",
        "guidance.food": "从前侧补光，避免手机挡住餐盘。",
        "guidance.product": "把光放在左前方，减少厚重阴影。",
        "guidance.meeting": "补光保持柔和，让视频里的脸更自然。",
        "guidance.nightRoom": "暖光靠近脸部，保留夜晚房间氛围。",
        "light.title": "屏幕柔光",
        "light.subtitle": "调节亮度和色调，然后打开全屏补光。",
        "light.brightness": "亮度",
        "light.tone": "色调",
        "light.distance": "距离",
        "light.start": "开启柔光",
        "light.close": "关闭",
        "light.full.title": "柔光已开启",
        "light.saved": "已保存到本机",
        "light.torch": "后置手电筒",
        "light.torch.on": "手电筒已开",
        "light.torch.off": "手电筒已关",
        "light.torch.unavailable": "此设备不可用",
        "scene.title": "场景预设",
        "scene.subtitle": "选择常用场景，参数会保存在本机。",
        "scene.selfie": "自拍头像",
        "scene.selfie.subtitle": "暖肤补光，阴影更柔",
        "scene.food": "餐厅食物",
        "scene.food.subtitle": "暗光餐厅颜色更干净",
        "scene.product": "商品照片",
        "scene.product.subtitle": "细节更清楚，阴影更少",
        "scene.meeting": "视频会议",
        "scene.meeting.subtitle": "柔和常亮补光",
        "scene.nightRoom": "夜晚房间",
        "scene.nightRoom.subtitle": "低光环境的暖色补光",
        "scene.selected": "预设已应用",
        "records.title": "本地记录",
        "records.subtitle": "最近参数只保存在这台 iPhone 上。",
        "records.empty": "应用推荐或预设后会生成记录。",
        "records.restored": "记录已恢复",
        "records.clear": "清空记录",
        "settings.title": "设置",
        "settings.subtitle": "本地偏好和应用信息。",
        "settings.language": "语言",
        "settings.system": "跟随系统",
        "settings.privacy": "隐私政策",
        "settings.support": "支持",
        "settings.version": "版本 1.0.0",
        "settings.localOnly": "本地工具 App。没有账号、分析、广告或后端。",
        "settings.languageChanged": "语言已保存",
        "common.score": "评分",
        "common.apply": "应用",
        "common.current": "当前",
        "common.done": "完成"
    ],
    .japanese: [
        "app.name": "グロウメイト",
        "tab.meter": "測光",
        "tab.light": "ライト",
        "tab.scenes": "シーン",
        "tab.records": "履歴",
        "tab.settings": "設定",
        "meter.title": "ソフトライト測光",
        "meter.subtitle": "端末内のカメラプレビューで測光し、画面補助光を提案します。",
        "meter.permission.title": "カメラへのアクセスが必要です",
        "meter.permission.body": "GlowMateは明るさの推定を端末内で行います。画像はアップロードされません。",
        "meter.permission.button": "カメラを許可",
        "meter.demo": "スクリーンショット用デモ",
        "meter.current": "現在の状態",
        "meter.recommendation": "おすすめ設定",
        "meter.apply": "ライトを適用",
        "meter.applied": "ライトに適用しました",
        "meter.noFrame": "ローカル光サンプルを待機中",
        "issue.tooDark": "顔まわりが暗い",
        "issue.tooBright": "光が強すぎます",
        "issue.cool": "光が青白い",
        "issue.yellow": "光が黄色い",
        "issue.balanced": "光は安定しています",
        "reason.tooDark": "画面ライトを強め、顔に近づけると影がやわらぎます。",
        "reason.tooBright": "補助光を弱めると白飛びを抑えられます。",
        "reason.cool": "暖かい肌ライトで自然な色に近づけます。",
        "reason.yellow": "自然な白で黄色かぶりを抑えます。",
        "reason.balanced": "中程度の補助光で自然なキャッチライトを作れます。",
        "headline.tooDark": "暖かい肌ライトを強めに",
        "headline.tooBright": "自然光をやわらかく",
        "headline.cool": "暖かい肌ライト",
        "headline.yellow": "自然な白で補正",
        "headline.balanced": "バランスのよいソフトライト",
        "tone.warmSkin": "ウォーム肌",
        "tone.naturalWhite": "ナチュラル白",
        "tone.coolWhite": "クール白",
        "tone.blush": "ブラッシュ",
        "distance.close": "25-35 cm",
        "distance.table": "35-50 cm",
        "distance.product": "40-60 cm",
        "distance.meeting": "45-70 cm",
        "guidance.selfie": "スマホを目線より少し上に置き、画面を顔に向けます。",
        "guidance.food": "前方の横から照らし、皿をスマホで隠さないようにします。",
        "guidance.product": "左前から照らすと重い影を減らせます。",
        "guidance.meeting": "やさしい常時ライトで自然な顔色にします。",
        "guidance.nightRoom": "暖かい光を顔に近づけ、夜の雰囲気を残します。",
        "light.title": "画面ソフトライト",
        "light.subtitle": "明るさと色を調整し、全画面ライトを開きます。",
        "light.brightness": "明るさ",
        "light.tone": "色",
        "light.distance": "距離",
        "light.start": "ソフトライト開始",
        "light.close": "閉じる",
        "light.full.title": "ソフトライト中",
        "light.saved": "端末に保存済み",
        "light.torch": "背面ライト",
        "light.torch.on": "ライトオン",
        "light.torch.off": "ライトオフ",
        "light.torch.unavailable": "この端末では利用できません",
        "scene.title": "シーン設定",
        "scene.subtitle": "よく使う設定を選ぶと端末内に保存されます。",
        "scene.selfie": "セルフィー",
        "scene.selfie.subtitle": "暖かい顔ライトと柔らかい影",
        "scene.food": "料理写真",
        "scene.food.subtitle": "暗い店内でも色をきれいに",
        "scene.product": "商品撮影",
        "scene.product.subtitle": "細部を見せ、影を軽く",
        "scene.meeting": "ビデオ会議",
        "scene.meeting.subtitle": "やさしい常時ライト",
        "scene.nightRoom": "夜の部屋",
        "scene.nightRoom.subtitle": "低照度向けの暖かい補助光",
        "scene.selected": "プリセットを適用しました",
        "records.title": "ローカル履歴",
        "records.subtitle": "最近の設定はこのiPhoneだけに保存されます。",
        "records.empty": "おすすめやプリセットを適用すると履歴が作成されます。",
        "records.restored": "履歴を復元しました",
        "records.clear": "履歴を消去",
        "settings.title": "設定",
        "settings.subtitle": "ローカル設定とアプリ情報。",
        "settings.language": "言語",
        "settings.system": "システムに合わせる",
        "settings.privacy": "プライバシーポリシー",
        "settings.support": "サポート",
        "settings.version": "バージョン 1.0.0",
        "settings.localOnly": "ローカル専用アプリ。アカウント、分析、広告、バックエンドはありません。",
        "settings.languageChanged": "言語を保存しました",
        "common.score": "スコア",
        "common.apply": "適用",
        "common.current": "現在",
        "common.done": "完了"
    ]
]
